name: Friends
api: 3.0.2
version: 2.0.0
main: SlashMC\Friends
author: SlashMC
website: https://VastLabsBE.de/vote
commands:
    friend:
        description: FreundesSystem
        aliases: [f, freunde, friends]
