name: Friends
api: 3.1.1
version: 2.0
main: SlashMC\Friends
author: SlashMC
website: https://worldplanet.ml/
commands:
    friend:
        description: FreundesSystem
        aliases: [f, freunde, friends]
